---
name: Barcode Buddy for Grocy
version: dev-docker-based
slug: bbuddy-grocy
description: Barcode system for Grocy
url: https://github.com/Forceu/barcodebuddy
webui: http://[HOST]:[PORT:80]
panel_icon: mdi:barcode-scan
startup: system
arch:
- aarch64
- amd64
- armv7
- i386
boot: auto
init: false
map:
- config:rw
- ssl
ports:
  80/tcp: 8621
ports_description:
  80/tcp: Web interface
options:
  require_api_key: false
  disable_auth: false
  debug: false
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
schema:
  require_api_key: bool
  disable_auth: bool
  debug: bool
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
